notifications:
  email: false

env:
  global:
    - RELEASE_BRANCH="master"

language: c
os:
- linux
- osx
sudo: required
services:
  - docker
git:
  submodules: true
compiler:
- gcc
addons:
  apt:
    packages:
    - git
    - gcc
    - make
    - cmake
    - lua5.1
    - luarocks
    - liblua5.1-0-dev

script:
  - make check

